services:
  postgres:
    container_name: financial-management-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financial-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: financial-management-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - financial-network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    name: financial-management-postgres-data
  pgadmin_data:
    name: financial-management-pgadmin-data

networks:
  financial-network:
    name: financial-management-network
    driver: bridge