services:
  dev-db:
    container_name: financial-management-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financial-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  test-db:
    container_name: financial-management-test-db
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_management
    networks:
      - financial-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
    name: financial-management-postgres-data

networks:
  financial-network:
    name: financial-management-network
    driver: bridge