name: Lint and Test

on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'fix/*'
      - 'ci/*'
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js / pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
      - name: Install Dependencies
        run: pnpm install
      - name: Run Linter
        run: pnpm run lint
      - name: Run Tests
        run: pnpm test
        