name: Lint and Test

on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'fix/*'
      - 'ci/*'
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test